apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: longstartup
  name: longstartup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: longstartup
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: longstartup
    spec:
      containers:
      - image: jrkessl/probes:v11
        name: probes
        resources: {}
        ports:
        - containerPort: 8080
        env: 
          - name: READYCOUNTER
            value: "20"
        livenessProbe:
          httpGet:
            path: /main
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 1            
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: longstartup
spec:
  selector:
    app: longstartup
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
