apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: readiness
  name: readiness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readiness
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: readiness
    spec:
      containers:
      - image: jrkessl/probes:v10
        name: probes
        resources: {}
        ports:
        - containerPort: 8080
        env: 
          - name: READYCOUNTER
            value: "20"
        livenessProbe:
          httpGet:
            path: /safe
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 8
        startupProbe:
          httpGet:
            path: /safe
            port: 8080
          failureThreshold: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /safe
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 1
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: readiness
spec:
  selector:
    app: readiness
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
