apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: long-startup
  name: long-startup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: long-startup
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: long-startup
    spec:
      containers:
      - image: jrkessl/probes:long-startup_v07
        name: probes
        resources: {}
        ports:
        - containerPort: 8080
        env: 
          - name: READYCOUNTER
            value: "10"
      terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: Service
metadata:
  name: long-startup
spec:
  selector:
    app: long-startup
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
