apiVersion: v1
kind: Pod
metadata:
  name: simplest-watcher
spec:
  containers:
    - image: jrkessl/ubuntu
      name: probes
      command: ['/bin/sh', '-c', ' echo "hello kube" && cp /home/myscript.sh /tmp && chmod 777 /tmp/myscript.sh && /tmp/myscript.sh'] 
      resources: {}
      volumeMounts:
        - name: config-volume
          mountPath: /home/
  volumes:
    - name: config-volume
      configMap:
        name: configmap-script
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-script
data:
  myscript.sh: |-
    #!/bin/bash
    while true; do
      curl -sS -w "%{http_code}" simplest:8080/business
      sleep 1
    done
