apiVersion: v1
kind: Pod
metadata:
  labels:
    app: simplest-watcher
  name: simplest-watcher
spec:
  containers:
  - image: ubuntu
    name: probes
    command: ["/bin/bash"]
    args: ["-c", "echo \"hello world\""]
    resources: {}
  terminationGracePeriodSeconds: 0
