apiVersion: v1
kind: Pod
metadata:
  name: simplest-watcher
spec:
  containers:
    - image: ubuntu
      name: probes
      # command: ["/bin/bash"]
      # args: ["-c", "echo \"hello world with sleep\"", ";", "sleep", "10"]
      command: ["/bin/bash"]
      args: ["-c", "ls -la /home/"]
      # command: ["/bin/sh", "-c", "sleep 28800"] # 28800 = 8 hours
      resources: {}
  restartPolicy: Never
  terminationGracePeriodSeconds: 0



