apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simplest-watcher
  name: simplest-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simplest-watcher
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simplest-watcher
    spec:
      restartPolicy: Always 
      containers:
      - image: ubuntu
        name: probes
        command: ["/bin/bash"]
        args: ["-c", "echo \"hello world\""]
        resources: {}
      terminationGracePeriodSeconds: 0
